version: "3.3"

services:
    webapp:
        build: .
        container_name: django-finance-db
        volumes:
            - ./app:/usr/src/app
        env_file: .env
        ports:
            - 4444:4444